import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsIn,
  IsInt,
  IsNumber,
  IsOptional,
  IsPositive,
  IsString,
  MaxLength,
  Min,
  MinLength,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";

export class ListingAttributeValueInputDto {
  @IsString()
  @MinLength(1)
  attributeKey!: string;

  attributeValue!: unknown;
}

export class ListingAvailabilityBlockInputDto {
  @IsDateString()
  startDate!: string;

  @IsDateString()
  endDate!: string;

  @IsOptional()
  @IsIn(["AVAILABLE", "BLOCKED", "BOOKED", "MAINTENANCE"])
  status?: "AVAILABLE" | "BLOCKED" | "BOOKED" | "MAINTENANCE";

  @IsOptional()
  @IsInt()
  @Min(1)
  quantity?: number;

  @IsOptional()
  @IsString()
  reason?: string;
}

export class CreateListingDto {
  @IsString()
  categoryId!: string;

  // cityId + streetId + addressNumber are the source of truth for a listing
  // address. pickupAddressText / pickupLat / pickupLng are derived fields,
  // generated by the backend from these three — never accepted as input.
  @IsString()
  cityId!: string;

  @IsString()
  streetId!: string;

  @IsInt()
  @Min(1)
  addressNumber!: number;

  @IsString()
  @MinLength(2)
  @MaxLength(160)
  titleHe!: string;

  @IsString()
  @MinLength(2)
  @MaxLength(160)
  titleEn!: string;

  @IsString()
  @MinLength(10)
  descriptionHe!: string;

  @IsString()
  @MinLength(10)
  descriptionEn!: string;

  @IsOptional()
  @IsString()
  suitableFor?: string;

  @IsOptional()
  @IsString()
  mainUses?: string;

  @IsNumber()
  @IsPositive()
  basePriceDaily!: number;

  @IsNumber()
  @Min(0)
  depositAmount!: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  popularityScore?: number;

  @IsOptional()
  @IsNumber()
  manualPriorityBoost?: number;

  @IsOptional()
  @IsString()
  pickupInstructions?: string;

  @IsBoolean()
  deliverySupported!: boolean;

  @IsOptional()
  includedItems?: string[];

  @IsOptional()
  @IsString()
  cancellationPolicy?: string;

  @IsOptional()
  @IsString()
  returnTerms?: string;

  @IsOptional()
  @IsBoolean()
  requiresOperator?: boolean;

  @IsOptional()
  @IsBoolean()
  setupRequired?: boolean;

  @IsInt()
  @Min(1)
  inventoryCount!: number;

  @IsInt()
  @Min(1)
  minRentalDays!: number;

  @IsInt()
  @Min(1)
  maxRentalDays!: number;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ListingAttributeValueInputDto)
  attributeValues?: ListingAttributeValueInputDto[];

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ListingAvailabilityBlockInputDto)
  availabilityBlocks?: ListingAvailabilityBlockInputDto[];
}
