export const demoCategories = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    slug: "photo-video",
    nameHe: "צילום ווידאו",
    nameEn: "Photo & Video",
    children: [],
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    slug: "events",
    nameHe: "אירועים",
    nameEn: "Events",
    children: [],
  },
];

export const demoListings = [
  {
    id: "listing-1",
    titleHe: "מצלמת Sony A7 IV",
    titleEn: "Sony A7 IV Camera",
    descriptionHe: "מצלמה מירורלס מקצועית עם שתי סוללות, מטען, רצועה וערכת ניקוי. זמינה לאיסוף מתל אביב.",
    descriptionEn: "High-end mirrorless camera with lens kit and batteries.",
    basePriceDaily: 280,
    lender: { displayName: "Studio North", averageRating: 4.9, completedTransactionsCount: 146 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-2",
    titleHe: "סט תאורה LED כפול",
    titleEn: "Dual LED Light Kit",
    descriptionHe: "שתי יחידות תאורה ניידות, חצובות ונרתיק. מתאים לצילומים ופנלים.",
    descriptionEn: "Portable lighting set for shoots and interviews.",
    basePriceDaily: 190,
    lender: { displayName: "RentLab TLV", averageRating: 4.7, completedTransactionsCount: 82 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-3",
    titleHe: "רחפן DJI Air 3",
    titleEn: "DJI Air 3 Drone",
    descriptionHe: "רחפן מקצועי עם שתי מצלמות, 3 סוללות ומזוודת נשיאה. מתאים לצילומי נוף ואירועים.",
    descriptionEn: "Professional drone with dual cameras and 3 batteries.",
    basePriceDaily: 350,
    lender: { displayName: "SkyRent", averageRating: 4.8, completedTransactionsCount: 63 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-4",
    titleHe: "מקרן 4K Ultra HD",
    titleEn: "4K Ultra HD Projector",
    descriptionHe: "מקרן נייד בהירות גבוהה עם חיבורי HDMI ו-USB. מתאים לאירועים ומצגות.",
    descriptionEn: "Portable high-brightness projector for events and presentations.",
    basePriceDaily: 250,
    lender: { displayName: "EventGear TLV", averageRating: 4.6, completedTransactionsCount: 101 },
    category: { nameHe: "אירועים" },
    media: [],
  },
  {
    id: "listing-5",
    titleHe: "מצלמת GoPro Hero 12",
    titleEn: "GoPro Hero 12",
    descriptionHe: "מצלמת אקשן עמידה במים עם ערכת אביזרים מלאה, עמדות הרכבה ושני בטריות.",
    descriptionEn: "Waterproof action camera with full accessory kit.",
    basePriceDaily: 120,
    lender: { displayName: "Budget Rentals", averageRating: 4.5, completedTransactionsCount: 209 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-6",
    titleHe: "חצובה מקצועית 190cm",
    titleEn: "Professional Tripod 190cm",
    descriptionHe: "חצובה אלומיניום יציבה עד גובה 190 ס\"מ עם ראש טייגי. כוללת תיק נשיאה.",
    descriptionEn: "Sturdy aluminum tripod with ball head and carry bag.",
    basePriceDaily: 80,
    lender: { displayName: "Studio North", averageRating: 4.9, completedTransactionsCount: 146 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-7",
    titleHe: "מיקרופון RØDE VideoMic Pro",
    titleEn: "RØDE VideoMic Pro",
    descriptionHe: "מיקרופון כיווני על-גבי מצלמה עם ביטול רעשי רקע. מתאים לצילומי שדה וריאיונות.",
    descriptionEn: "Directional on-camera microphone with ambient noise reduction.",
    basePriceDaily: 90,
    lender: { displayName: "RentLab TLV", averageRating: 4.7, completedTransactionsCount: 82 },
    category: { nameHe: "אודיו" },
    media: [],
  },
  {
    id: "listing-8",
    titleHe: "מיקסר שמע 16 ערוצים",
    titleEn: "16-Channel Audio Mixer",
    descriptionHe: "מיקסר אנלוגי מקצועי עם אפקטים מובנים ואיקולייזר. מתאים להופעות ואירועים.",
    descriptionEn: "Professional 16-channel analog mixer for live events.",
    basePriceDaily: 180,
    lender: { displayName: "SoundSystems IL", averageRating: 4.8, completedTransactionsCount: 57 },
    category: { nameHe: "אודיו" },
    media: [],
  },
  {
    id: "listing-9",
    titleHe: "מצלמת Sony FX3 קולנוע",
    titleEn: "Sony FX3 Cinema Camera",
    descriptionHe: "מצלמת קולנוע מלא עם מצב S-Cinetone, קולט חום ויכולות 4K/120fps. לסרטים ופרסומות.",
    descriptionEn: "Full-frame cinema camera with 4K/120fps and S-Cinetone.",
    basePriceDaily: 450,
    lender: { displayName: "Studio North", averageRating: 4.9, completedTransactionsCount: 146 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-10",
    titleHe: "ערכת פלאש אולפן 3 ראשים",
    titleEn: "3-Head Studio Flash Kit",
    descriptionHe: "ערכת פלאש מקצועית עם שלושה ראשי אור, מטריות ובוקסי אור. מושלם לצילומי פורטרט.",
    descriptionEn: "Professional 3-head flash kit with umbrellas and softboxes.",
    basePriceDaily: 160,
    lender: { displayName: "PhotoPro Haifa", averageRating: 4.6, completedTransactionsCount: 74 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
  {
    id: "listing-11",
    titleHe: "מערכת קול ניידת JBL",
    titleEn: "JBL Portable Sound System",
    descriptionHe: "מערכת הגברה ניידת 1000W עם אלחוטי ומיקרופון. מתאימה לאירועים קטנים-בינוניים.",
    descriptionEn: "1000W portable PA system with wireless mic.",
    basePriceDaily: 220,
    lender: { displayName: "EventGear TLV", averageRating: 4.6, completedTransactionsCount: 101 },
    category: { nameHe: "אירועים" },
    media: [],
  },
  {
    id: "listing-12",
    titleHe: "מצלמת Canon EOS R5",
    titleEn: "Canon EOS R5",
    descriptionHe: "מצלמה מקצועית 45 מגה פיקסל עם וידאו 8K. ערכה כוללת שתי עדשות ו-4 סוללות.",
    descriptionEn: "45MP professional mirrorless with 8K video and two lenses.",
    basePriceDaily: 320,
    lender: { displayName: "RentLab TLV", averageRating: 4.7, completedTransactionsCount: 82 },
    category: { nameHe: "צילום ווידאו" },
    media: [],
  },
];

export const demoListing = {
  id: "listing-1",
  titleHe: "מצלמת Sony A7 IV",
  titleEn: "Sony A7 IV Camera",
  descriptionHe:
    "מצלמה מקצועית להשכרה עם שתי סוללות, מטען, רצועה וערכת ניקוי. זמינה לאיסוף מתל אביב או משלוח בתיאום.",
  descriptionEn: "Professional camera with lens, batteries, charger, and cleaning kit.",
  basePriceDaily: 280,
  depositAmount: 1200,
  category: {
    nameHe: "צילום ווידאו",
  },
  lender: {
    displayName: "Studio North",
    averageRating: 4.9,
    completedTransactionsCount: 146,
    deliveryWindows: [],
  },
  media: [],
  attributeValues: [
    { attributeKey: "sensor", attributeValue: "full-frame" },
    { attributeKey: "video", attributeValue: "4k" },
  ],
  pricingRules: [],
  reviews: [
    {
      id: "review-1",
      rating: 5,
      text: "ציוד שמור, תקשורת מעולה ואיסוף מהיר.",
      reviewer: { fullName: "נועה כהן" },
    },
  ],
  completenessHints: ["הוספת תמונה רחבה של הערכה המלאה תשפר את ההמרה."],
};

export const demoBundleResults = {
  searchId: "demo-search",
  requestedItems: [
    { slotKey: "camera", quantity: 1 },
    { slotKey: "tripod", quantity: 1 },
    { slotKey: "lights", quantity: 1 },
  ],
  topRankedBundles: [
    {
      id: "bundle-1",
      label: "best-balanced",
      overallScore: 8.8,
      scores: {
        price: 7.4,
        reliability: 9.1,
        logistics: 8.5,
        availability: 8.7,
        quality: 9.0,
        stability: 8.8,
      },
      explanation: {
        he: {
          title: "האופציה המאוזנת ביותר",
          subtitle: "₪840, 2 נקודות איסוף, 8.1 ק\"מ משוער, התאמה מלאה לתאריכים",
          strengths: ["מלווים עם אמינות גבוהה", "2 נקודות איסוף בלבד", "ביצועים מאוזנים לאורך כל המדדים"],
          tradeoffs: ["המחיר אינו מהזולים בתוצאות"],
        },
        chips: ["highly rated lenders", "2 pickup points only", "exact date match"],
      },
      pickupPointsCount: 2,
      totalEstimatedDistanceKm: 8.1,
      totalBundlePrice: 840,
      exactAvailabilityFit: true,
      includedItems: [
        {
          slotKey: "camera",
          listingId: "listing-1",
          listingTitleHe: "מצלמת Sony A7 IV",
          categoryNameHe: "צילום ווידאו",
        },
      ],
    },
    {
      id: "bundle-2",
      label: "best-price",
      overallScore: 8.1,
      scores: {
        price: 9.2,
        reliability: 7.3,
        logistics: 6.7,
        availability: 8.8,
        quality: 7.5,
        stability: 7.6,
      },
      explanation: {
        he: {
          title: "האופציה החסכונית",
          subtitle: "₪710, 3 נקודות איסוף, 15.4 ק\"מ משוער, התאמה מלאה לתאריכים",
          strengths: ["יחס מחיר טוב מול השוק"],
          tradeoffs: ["נוחות האיסוף נמוכה יחסית"],
        },
        chips: ["budget-friendly"],
      },
      pickupPointsCount: 3,
      totalEstimatedDistanceKm: 15.4,
      totalBundlePrice: 710,
      exactAvailabilityFit: true,
      includedItems: [],
    },
    {
      id: "bundle-3",
      label: "easiest-pickup",
      overallScore: 8.4,
      scores: {
        price: 7.0,
        reliability: 8.3,
        logistics: 9.4,
        availability: 8.0,
        quality: 8.1,
        stability: 8.1,
      },
      explanation: {
        he: {
          title: "האופציה הנוחה ביותר לאיסוף",
          subtitle: "₪860, נקודת איסוף אחת, 4.8 ק\"מ משוער, התאמה מלאה לתאריכים",
          strengths: ["כל הפריטים ממלווה אחד", "נקודת איסוף אחת בלבד"],
          tradeoffs: ["המחיר אינו מהזולים בתוצאות"],
        },
        chips: ["same lender", "2 pickup points only", "exact date match"],
      },
      pickupPointsCount: 1,
      totalEstimatedDistanceKm: 4.8,
      totalBundlePrice: 860,
      exactAvailabilityFit: true,
      includedItems: [],
    },
  ],
  alternateBundles: [],
  labels: {
    bestBalanced: "bundle-1",
    bestPrice: "bundle-2",
    easiestPickup: "bundle-3",
  },
  observability: {
    timings: {
      candidateFetchMs: 42,
      bundleGenerationMs: 13,
      scoringMs: 7,
    },
  },
};

export const demoOverview = {
  users: 42,
  lenders: 9,
  renters: 25,
  listings: 31,
  bundleSearches: 108,
  disputes: 2,
};

export const demoAdminCategories = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    parentId: null,
    slug: "photo-video",
    nameHe: "צילום ווידאו",
    nameEn: "Photo & Video",
    status: "ACTIVE",
    _count: { listings: 8 },
  },
  {
    id: "11111111-1111-4111-8111-111111111112",
    parentId: "11111111-1111-4111-8111-111111111111",
    slug: "cameras",
    nameHe: "מצלמות",
    nameEn: "Cameras",
    status: "ACTIVE",
    _count: { listings: 4 },
  },
  {
    id: "11111111-1111-4111-8111-111111111113",
    parentId: "11111111-1111-4111-8111-111111111111",
    slug: "tripods",
    nameHe: "חצובות",
    nameEn: "Tripods",
    status: "ACTIVE",
    _count: { listings: 3 },
  },
];

export const demoAdminCatalogOptions = {
  categories: demoAdminCategories,
  lenders: [
    {
      userId: "cccccccc-cccc-4ccc-8ccc-ccccccccccca",
      displayName: "Studio North",
      user: { id: "cccccccc-cccc-4ccc-8ccc-ccccccccccca", fullName: "Studio North", email: "studio-north@rentmatch.local" },
    },
    {
      userId: "cccccccc-cccc-4ccc-8ccc-cccccccccccb",
      displayName: "Budget Rentals",
      user: { id: "cccccccc-cccc-4ccc-8ccc-cccccccccccb", fullName: "Budget Rentals", email: "budget@rentmatch.local" },
    },
    {
      userId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      displayName: "OneStop TLV",
      user: { id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc", fullName: "OneStop TLV", email: "onestop@rentmatch.local" },
    },
  ],
};

export const demoAdminListings = [
  {
    id: "30000000-0000-4000-8000-000000000001",
    titleHe: "Sony A7 IV עם ערכה מלאה",
    titleEn: "Sony A7 IV Full Kit",
    descriptionHe: "מצלמה מקצועית עם עדשה, שתי סוללות, מטען וערכת ניקוי.",
    descriptionEn: "Professional mirrorless camera with lens kit and accessories.",
    status: "ACTIVE",
    condition: "LIKE_NEW",
    basePriceDaily: 280,
    depositAmount: 1200,
    pickupAddressText: "פלורנטין, תל אביב",
    pickupLat: 32.074,
    pickupLng: 34.792,
    deliverySupported: true,
    inventoryCount: 2,
    minRentalDays: 1,
    maxRentalDays: 14,
    lenderId: "cccccccc-cccc-4ccc-8ccc-ccccccccccca",
    categoryId: "11111111-1111-4111-8111-111111111112",
    lender: {
      displayName: "Studio North",
      user: { fullName: "Studio North" },
    },
    category: {
      nameHe: "מצלמות",
    },
    media: [],
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    titleHe: "Fujifilm X-H2 בחבילת אולפן",
    titleEn: "Fujifilm X-H2 Studio Bundle",
    descriptionHe: "מצלמה איכותית במרחק קצר, חלק מחבילת ציוד מאותו מלווה.",
    descriptionEn: "High quality camera from a central lender offering multiple items.",
    status: "PENDING_REVIEW",
    condition: "LIKE_NEW",
    basePriceDaily: 295,
    depositAmount: 1300,
    pickupAddressText: "מרכז תל אביב",
    pickupLat: 32.083,
    pickupLng: 34.781,
    deliverySupported: true,
    inventoryCount: 1,
    minRentalDays: 1,
    maxRentalDays: 14,
    lenderId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    categoryId: "11111111-1111-4111-8111-111111111112",
    lender: {
      displayName: "OneStop TLV",
      user: { fullName: "OneStop TLV" },
    },
    category: {
      nameHe: "מצלמות",
    },
    media: [],
  },
];
